import React from 'react';
import { Link } from 'react-router-dom';

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 font-sans">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-xl overflow-hidden border border-slate-200">
        
        {/* Header */}
        <div className="bg-welfare-blue px-6 py-8 sm:px-10">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl sm:text-3xl font-bold text-white">Privacy Policy & Commercial Terms</h1>
            <Link to="/register" className="text-blue-100 hover:text-white transition-colors flex items-center text-sm font-medium">
              <svg className="w-4 h-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
              Close
            </Link>
          </div>
          <p className="text-blue-200 mt-2 text-sm">Last Updated: December 14, 2025</p>
        </div>

        {/* Content */}
        <div className="px-6 py-8 sm:px-10 space-y-8 text-slate-600 leading-relaxed">
          
          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3 flex items-center">
              <span className="bg-blue-100 text-welfare-blue text-xs px-2 py-1 rounded-md mr-2">1</span>
              Data Collection & Acceptance
            </h2>
            <p>
              By registering your business on the Welfare School Community Directory ("The Platform"), you explicitly acknowledge and agree to the collection, storage, and processing of the personal and business data provided during the registration process. This includes, but is not limited to, your name, business name, contact details, images, and descriptions.
            </p>
          </section>

          <section className="bg-blue-50 p-6 rounded-xl border border-blue-100">
            <h2 className="text-xl font-bold text-welfare-blue mb-3 flex items-center">
              <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              2. Commercial Use Authorization
            </h2>
            <p className="font-medium text-slate-800 mb-2">
              You hereby grant The Platform a worldwide, non-exclusive, royalty-free, and perpetual license to use your data for commercial purposes.
            </p>
            <p className="text-sm">
              This specifically includes:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-sm">
              <li>Displaying your business in public and private directories.</li>
              <li>Using your business name and images in marketing materials, newsletters, and social media campaigns to promote the Welfare community.</li>
              <li>Sharing aggregated, non-personally identifiable insights with third-party partners.</li>
              <li>Monetizing the directory through featured listings or advertisements in the future.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">3. AI Processing</h2>
            <p>
              You understand that parts of your profile, including descriptions and tags, may be generated or optimized using Artificial Intelligence (AI). While you have the ability to edit this content, The Platform is not liable for inaccuracies generated by AI models.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">4. User Rights & Data Removal</h2>
            <p>
              You retain the right to request the modification or removal of your business listing at any time. To exercise these rights, please contact the administration. Upon request, your public data will be removed from the active directory within 30 days.
            </p>
          </section>

          <section className="pt-6 border-t border-slate-200">
            <p className="text-xs text-slate-400 text-center">
              By proceeding with the registration, you confirm that you have the legal authority to represent the business listed and accept these terms without reservation.
            </p>
          </section>

        </div>
        
        {/* Footer */}
        <div className="bg-slate-50 px-6 py-4 sm:px-10 flex justify-end border-t border-slate-200">
           <Link 
             to="/register" 
             className="px-6 py-2 bg-welfare-blue text-white rounded-lg font-semibold shadow-sm hover:bg-blue-700 transition-colors"
           >
             I Understand
           </Link>
        </div>

      </div>
    </div>
  );
};

export default PrivacyPolicy;
